# .streamlit/secrets.toml

SUPABASE_URL = "https://fenecmrbaxhonjmssfjv.supabase.co"
SUPABASE_KEY = "sbp_3aef105dd27cd24a3db363a1012a4aa9dcf9ec7c"
GROQ_API_KEY = "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"
